### ISSUE TITLE
Compiling guira on Debian 7

### ISSUE THREAD

**Issue by stewartwebb** [sir-murray/guira#1]
Trying to compile Guira on Debian 7 and getting error:

```
ocamlfind ocamlc -safe-string -w +A-4 -c sexp.mli
ocamlc: unknown option `-safe-string'.
```

Wrong ocaml version or something?

**Comment by ii8** [comment]
Yes, you need at least 4.02.0
If your distributions ocaml is out of date, you can try installing from opam.

**Comment by stewartwebb** [comment]
Removed ocaml and ocaml-findlib with debian package manager. Re-installed using opam. All fixed. What a great piece of software you have here, it's a shame more people aren't using it.
